# Generated by Django 3.1.7 on 2021-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
