# Generated by Django 3.1.7 on 2021-08-31 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(unique=True)),
                ('courier_type', models.CharField(max_length=4)),
                ('capacity', models.IntegerField(default=None)),
                ('assign_time', models.DateTimeField(default=None, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('earnings', models.IntegerField(default=0)),
                ('count_of_delivery', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(50)])),
                ('region', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(default=None, null=True)),
                ('counted', models.BooleanField(default=False)),
                ('type_of_courier_assign', models.CharField(default='', max_length=5)),
                ('cnt_of_delivery', models.IntegerField(default=0)),
                ('courier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candy_store.courieritem')),
                ('delivery_hours', models.ManyToManyField(related_name='delivery_hours', to='candy_store.DeliveryHours')),
            ],
        ),
        migrations.AddField(
            model_name='courieritem',
            name='regions',
            field=models.ManyToManyField(related_name='regions', to='candy_store.Region'),
        ),
        migrations.AddField(
            model_name='courieritem',
            name='working_hours',
            field=models.ManyToManyField(related_name='working_hours', to='candy_store.WorkingHours'),
        ),
    ]
